# Generated by Django 4.2.1 on 2023-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Create",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=300)),
                ("Author", models.CharField(max_length=300)),
                ("File", models.FileField(upload_to="documents/")),
                ("Time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
