# Generated by Django 4.2.1 on 2023-06-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="create",
            name="Comment",
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name="create",
            name="Title",
            field=models.CharField(max_length=300),
        ),
    ]
